// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using post_office_management_app.Data;

namespace post_office_management.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("post_office_management_app.Models.BagOfLetters", b =>
                {
                    b.Property<string>("BagId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DestinationCountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LettersCount")
                        .HasColumnType("int");

                    b.Property<string>("ShipmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("BagId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("BagOfLetters");
                });

            modelBuilder.Entity("post_office_management_app.Models.BagOfParcels", b =>
                {
                    b.Property<string>("BagId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DestinationCountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipmentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BagId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("BagOfParcels");
                });

            modelBuilder.Entity("post_office_management_app.Models.Parcel", b =>
                {
                    b.Property<string>("ParcelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BagId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BagOfParcelsBagId")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DestinationCountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("WeightInKg")
                        .HasColumnType("decimal(5,3)");

                    b.HasKey("ParcelId");

                    b.HasIndex("BagOfParcelsBagId");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("post_office_management_app.Models.Shipment", b =>
                {
                    b.Property<string>("ShipmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DestinationAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isFinalized")
                        .HasColumnType("bit");

                    b.HasKey("ShipmentId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("post_office_management_app.Models.BagOfLetters", b =>
                {
                    b.HasOne("post_office_management_app.Models.Shipment", "Shipment")
                        .WithMany("ListOfLetterBags")
                        .HasForeignKey("ShipmentId");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("post_office_management_app.Models.BagOfParcels", b =>
                {
                    b.HasOne("post_office_management_app.Models.Shipment", "Shipment")
                        .WithMany("ListOfParcelBags")
                        .HasForeignKey("ShipmentId");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("post_office_management_app.Models.Parcel", b =>
                {
                    b.HasOne("post_office_management_app.Models.BagOfParcels", null)
                        .WithMany("ListOfParcels")
                        .HasForeignKey("BagOfParcelsBagId");
                });

            modelBuilder.Entity("post_office_management_app.Models.BagOfParcels", b =>
                {
                    b.Navigation("ListOfParcels");
                });

            modelBuilder.Entity("post_office_management_app.Models.Shipment", b =>
                {
                    b.Navigation("ListOfLetterBags");

                    b.Navigation("ListOfParcelBags");
                });
#pragma warning restore 612, 618
        }
    }
}
